
#+TITLE:     Internet of Things code deployment metrics: probleemstelling
#+AUTHOR:    Ward Schodts, Xavier Goás Aguililla
#+EMAIL:     ward.schodts@student.kuleuven.be, xavier.goas@student.kuleuven.be
#+DATE:      maandag 10 november 2014

#+OPTIONS:   toc:nil

* Observatie
In WSNs wordt weinig gebruik gemaakt van de ingebedde rekenkracht en
opslagcapaciteit van de sensor nodes.
* Vraagstelling
Zou het mogelijk zijn om een andere aanpak te gebruiken, d.i. meer
berekeningen uit te voeren en meer data op te slaan op de sensor nodes
zelf, zonder verlies van performantie of energie-efficiëntie?
* Waarom
Als dit mogelijk was dan zouden we minder gebruik moeten maken van de
RF-antennes, die veel energie verbruiken. Eventueel kan dit zelfs ook
betere performantie opleveren, omdat er dan minder data over het
netwerk zou moeten overgedragen worden.
* Hypothese
Wij denken dat in bepaalde scenario's het beter is om bewerkingen op
de sensor nodes uit te voeren voor een efficiënter energiegebruik en
misschien zelfs betere performantie.
* Bewijs
Metingen die aantonen dat voor een gelijkaardige fysieke setup een
andere verdeling van de werklast binnen het WSN voordelen oplevert qua
energieverbruik en/of performantie vis-à-vis een klassiekere
werkverdeling.
* Vereisten
Het ontwikkelen van een tool die toelaat om de potentiële
energie-efficiëntie en performantie van een WSN te meten op basis van
welke types code (bv. adhv. vooraf gebenchmarkte API calls) waar
worden uitgevoerd.
